### ISSUE TITLE
Prevent screenshots while showing OTP codes.

### ISSUE THREAD

**Issue by sheesupport** [monich/harbour-foilauth#14]
Hi, I wonder if SFOS provides a feature to prevent making a screenshot while a applications is open.

The problem is generic and must be supported by the UI layer (IPC/DBUS layer?). 

The Android OS seems to provide FLAG_SECURE. Example of the problem:
https://github.com/google/google-authenticator-android/issues/50

So, to protect the auth code. Does SFOS has such flag? Could this be integrated into foilauth? 
Any comments on this would be great! Thx.

**Comment by monich** [comment]
AFAICT there's no such option. However, when a screenshot is taken, the system these days always shows a popup to alert the user that something is going on.
