### ISSUE TITLE
Support otpauth-migration://offline?data= QR codes

### ISSUE THREAD

**Issue by monich** [monich/harbour-foilauth#21]
Those get produced by Google Authenticator 's "Transfer accounts" => "Export accounts" feature and look like this:

![Screenshot_20210405_001](https://user-images.githubusercontent.com/5909522/113594144-f015d200-963f-11eb-8cd2-0d3b6c075443.png)

**Comment by monich** [comment]
Some support for those was added in version 1.0.17 but so far it only allows to pick one of the tokens encoded in such a QR code, still need to add UI for bulk import (add multiple tokens at once).

**Comment by monich** [comment]
Version 1.0.18 supports export of multiple tokens via otpauth-migration://offline QR code. Bulk import is the last missing piece.

**Comment by monich** [comment]
The last missing piece (bulk import) is implemented in version 1.1.3

Done!

**Comment by dawooddawood19890-byte** [comment]
[](url)

**Comment by dawooddawood19890-byte** [comment]
###

**Comment by mehmedserj9** [comment]
<img width="720" height="1600" alt="Image" src="https://github.com/user-attachments/assets/b715ecfc-2bda-486c-81ae-c947159f7e46" />

**Comment by monich** [comment]
<img width="540" height="1260" alt="Image" src="https://github.com/user-attachments/assets/04220a3f-eaaa-4aa3-a943-b4bd93ed0254" />
