### ISSUE TITLE
Handle timezones or time shift

### ISSUE THREAD

**Issue by sppg** [monich/harbour-foilauth#36]
Dear Sirs,
  We are very happy using this application, and we would like to ask for an improvement.
In fact, as we travel, we change the timezone and the TOTP is not working anymore, each time I had to change the date/time of the phone to get a working OTP then switch back to the local time.
Would it be possible to add an option of a timeshift in the application?
Thank you again for the great work
Best regards

**Comment by sppg** [comment]
Thank you very much @monich for your fast response.
In fact, the timezones are not updated that regularly on sailfishos, and I had the issue twice already (as I adjust the phone's time manually).
And of course, this improvement would help also in case of wrongly set timezone on the server.
I'm ready to betatest it whenever you ask me :)
Cheers

**Comment by monich** [comment]
Hehe, timeshift is already in the UI, being encrypted, restored and everything... Just not being used 🙂

**Comment by monich** [comment]
That was easy (495c1d0)

**Comment by monich** [comment]
Timeshift should work in release [1.1.8](https://github.com/monich/harbour-foilauth/releases/tag/1.1.8)

**Comment by sppg** [comment]
Thank you very much, the time I connected I found the 1.1.9 already :)

**Comment by monich** [comment]
Please test and if it works for you, close the issue

**Comment by sppg** [comment]
Works perfectly.
Thank you again
